name: NASA Project CI 
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: #reusable scripts used to automate the job
      - uses: actions/checkout@v2 #checkout the latest version of the code from master
      #checkout is built into github actions 
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install 
      - run: npm run build --prefix client